#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

name: release
on:
  push:
    tags:
      - 'v*'
jobs:
  publish:
    name: Publish image
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go

      - name: Set ENV vars
        run: |
          TAG=$(git describe --tags --always `git rev-list --tags --max-count=1`)
          echo "IMAGE_TAG"=$TAG >> $GITHUB_ENV
          echo "IMAGE_PREFIX_VCT"=ghcr.io/trustbloc/vct >> $GITHUB_ENV
          echo "IMAGE_PREFIX_LOG_SERVER"=ghcr.io/trustbloc/vct-log-server >> $GITHUB_ENV
          echo "IMAGE_PREFIX_LOG_SIGNER"=ghcr.io/trustbloc/vct-log-signer >> $GITHUB_ENV
          echo "IMAGE_PREFIX_MYSQL"=ghcr.io/trustbloc/vct-mysql >> $GITHUB_ENV
          echo "IMAGE_PREFIX_POSTGRES"=ghcr.io/trustbloc/vct-postgres >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_USER }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and Push container images (vct)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./images/vct/Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            ALPINE_VER=3.12
            GO_VER=1.16
            APP_FOLDER=vct
          push: true
          tags: |
            ${{ env.IMAGE_PREFIX_VCT }}:${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_PREFIX_VCT }}:latest

      - name: Build and Push container images (log-server)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./images/vct/Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            ALPINE_VER=3.12
            GO_VER=1.16
            APP_FOLDER=log_server
          push: true
          tags: |
            ${{ env.IMAGE_PREFIX_LOG_SERVER }}:${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_PREFIX_LOG_SERVER }}:latest

      - name: Build and Push container images (log-signer)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./images/vct/Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            ALPINE_VER=3.12
            GO_VER=1.16
            APP_FOLDER=log_signer
          push: true
          tags: |
            ${{ env.IMAGE_PREFIX_LOG_SIGNER }}:${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_PREFIX_LOG_SIGNER }}:latest

      - name: Build and Push container images (mysql)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./images/db/mysql/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_PREFIX_MYSQL }}:${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_PREFIX_MYSQL }}:latest

      - name: Build and Push container images (postgres)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./images/db/postgres/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_PREFIX_POSTGRES }}:${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_PREFIX_POSTGRES }}:latest

      - name: Build binaries (vct)
        run: make build-vct-dist build-log-server-dist build-log-signer-dist

      - name: Upload binaries and their SHA to Github Release
        uses: alexellis/upload-assets@0.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["./build/dist/bin/vct*", "./build/dist/bin/log-server*", "./build/dist/bin/log-signer*"]'
